### ISSUE TITLE
empty POST parameters 

### ISSUE THREAD

**Issue by ilvalerione** [palanik/CorsSlim#11]
Hello palanik! thanks to share this library!

The api works great in GET request, but in POST request when i retrieve parameters with:

$req = $app->request()->post();

$req is empty, but in developer console (Chrome) Request-Payload contains data.

Do you have tips?

Thanks in advance

**Comment by ilvalerione** [comment]
there was a missconfiguration on the client.

middleware works well, thanks

**Comment by palanik** [comment]
Glad it worked out.
