### ISSUE TITLE
How to dynamically load origin?

### ISSUE THREAD

**Issue by mromarreyes** [palanik/CorsSlim#15]
Hi, I have a column in a database table that stores the domain that an app will be accessing our API from. 

I would like to be able to dynamically load the domain from the database and include it as the origin option of the middleware. 

What is the best way to do this? I tried doing a query but it didn't work. How would I dynamically load a whitelist of domains?

**Comment by palanik** [comment]
Yes. You can do dynamic origins with CorsSlim.

You could do it in couple of ways.

I. Specify the whitelist array as the `origin` property of the options.

```
$whitelist = array("http://mozilla.com", "http://php.net", "http://github.com");
$corsslim = new \CorsSlim\CorsSlim(array("origin" => $whitelist));
$app->add(new \CorsSlim\CorsSlim());
```

Thanks to @CodeCommander for this [feature](https://github.com/palanik/CorsSlim/pull/10)

II. The `origin` property in the options can be a [callable](http://php.net/manual/en/language.types.callable.php). 
The callable function is called with the `origin` value in the request header. 

You could check the origin in the request header and decide whether to allow the request or not.
