### ISSUE TITLE
Install doesn't work with * only specific version

### ISSUE THREAD

**Issue by marvinosswald** [palanik/CorsSlim#6]
Installation didn't work until i switched to a specific version number, and then it downgraded my slim version from 2.6.3 to 2.4.0

Cheers Marv

**Comment by palanik** [comment]
@marvinosswald Did you try with 'dev-master' version?

**Comment by marvinosswald** [comment]
No only tried it with composer..

**Comment by palanik** [comment]
Like this `"palanik/corsslim": "dev-master"` in composer.json

**Comment by marvinosswald** [comment]
works :+1:
