### ISSUE TITLE
301 Permanent Moved on heroku

### ISSUE THREAD

**Issue by marvinosswald** [palanik/CorsSlim#7]
Can't figure why..  I use CorsSlim with default Settings and when I try to access it from another heroku repo I keep getting an `301 Permanent Moved` 
Any Ideas ?

EDIT: And If I try the same request with postman it works like charm...

request:

```
    Host: lavacal-api.heroku.com
    User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: de,en-US;q=0.7,en;q=0.3
    Accept-Encoding: gzip, deflate
    Origin: http://lavacal.herokuapp.com
    Access-Control-Request-Method: GET
    Access-Control-Request-Headers: apikey
    Connection: keep-alive
```

response:

```
    Connection: keep-alive
    Content-Length: 0
    Date: Mon, 20 Apr 2015 16:30:41 GMT
    Location: http://lavacal-api.herokuapp.com/api/v1/events
    Server: Cowboy
```

**Comment by max** [comment]
Saw your message on Ember Community. It looks like you're pinring `heroku.com`. Try using `herokuapp.com` instead. That's where your redirect goes to...

**Comment by palanik** [comment]
@max is correct. heroku.com url sends a 301 redirect response to herokuapp.com.

```
$ curl -I 'http://lavacal-api.heroku.com/api/v1/events'
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Server: Cowboy
Date: Tue, 21 Apr 2015 03:40:03 GMT
Content-Length: 0
Location: http://lavacal-api.herokuapp.com/api/v1/events
```

Thanks @max.

I also tried with a sample page making ajax requests to `http://lavacal-api.herokuapp.com/api/v1/events` and it worked flawlessly with correct CORS headers.

The reason it was working with postman was, by default postman is set to automatically follow redirects. You can change this behavior, in the settings. (Settings > Settings >Automatically follow redirects). You also need Interceptor to make this work.

HTH.
- P

**Comment by marvinosswald** [comment]
Oh man.. Thanks a lot guys :+1:  Rly didn't seen it.

**Comment by vishaljagtap-tudip** [comment]
hey guys, I have used hirokuapp.com but still I got moved permanently :(

**Comment by max** [comment]
@vishaljagtap-tudip You wrote `hirokuapp.com`. If that's just a typo in filing the issue ignore this message but the correct domain is `herokuapp.com`.
